# Generated by Django 4.2.13 on 2024-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivo', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
